packages:
  - apps/*
  - packages/*
  - tooling/*
  - '!**/test/**'

overrides:
  '@types/react': ^19.2.15
  '@types/react-dom': ^19.2.3

allowBuilds:
  esbuild: true
  protobufjs: true
  core-js: false
  serverless: false
  sharp: false
